// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmkrzsaslctwnpkkpqbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ta3J6c2FzbGN0d25wa2twcWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MjgwMDgsImV4cCI6MjA4NjAwNDAwOH0.tSuZMNLootxXBWPuskdiOaRLSVgEBuscTaAi2QKAuo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});


